apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kx9fod23y-python
  janus-idp.io/tekton: kx9fod23y-python
  backstage.io/kubernetes-id: kx9fod23y-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kx9fod23y-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
